live/anchor/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from . import views



urlpatterns = [
    # 前端用户
    url(r'^anchor_list/$', views.AnchorList.as_view(), name='anchor_list'),
    url(r'^anchor_add/$', views.AnchorAdd.as_view(), name='anchor_add'),
    url(r'^anchor_edit/(?P<pk>\w*)/$', views.AnchorEdit.as_view(), name='anchor_edit'),
    url(r'^anchor_audit/$', views.audit, name='anchor_audit'),

]

live/category/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from . import views



urlpatterns = [
    # 分类
    url(r'^category_list/$', views.CategoryList.as_view(), name='category_list'),
    url(r'^upload_picture/$', views.upload_picture, name='upload_picture'),


]

live/course/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include

from . import  views

urlpatterns = [
    # 前端用户
    url(r'^course_list/$', views.CourseList.as_view(), name='course_list'),
    url(r'^course_add/$', views.CourseAdd.as_view(), name='course_add'),
    url(r'^course_edit/(?P<pk>\w*)/$', views.CourseEdit.as_view(), name='course_edit'),
    url(r'^course_audit/$', views.audit, name='course_audit'),

  	#直播地址
    url(r'^live_room/(?P<pk>\w*)/$', views.LiveRoom.as_view(), name='live_room'),

]

live/live/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^anchor/', include('anchor.urls', namespace="anchor")),
    url(r'^course/', include('course.urls', namespace="course")),
    url(r'^category/', include('category.urls', namespace="category")),
    url(r'^audience/', include('audience.urls', namespace="audience")),
    url(r'^management/', include('management.urls', namespace="management")),
    url(r'^index/', include('index.urls', namespace="index")),




    #直播api
    url(r'^courses/', include('course.api_urls')),
    url(r'^categories/', include('category.api_urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

live/management/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib.auth.views import logout_then_login, password_change

from . import views



urlpatterns = [
    # 前端用户
    url(r'^management_list/$', views.AuthList.as_view(), name='management_list'),
    url(r'^management_add/$', views.AuthAdd.as_view(), name='management_add'),
    # url(r'^management_edit/(?P<pk>\w*)/$', views.AnchorEdit.as_view(), name='management_edit'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^login/$', views.LoginForm.as_view(), name='login'),



]

live/base/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

live/base/views.py
# -*- coding: utf-8 -*-
import operator
from django.shortcuts import render
from django.views.generic import ListView
from django import forms
from django.db.models import Q


class OwnerList(ListView):
    # 关键字查询field, subclass TODO: 子类未重写raise
    search_fields = None # ["description__contains", "charge_id__contains"]
    # datetime field TODO: 子类未重写raise
    datetime_fields = [] # ["createDate"]
    # default order sort TODO: 子类未重写raise
    default_order_sort_field = None # ["-createDate"]
    # models TODO: 子类未重写raise
    model_class = None
    form_fields = None # ["channel", "status", "merchant"]
    # 默认查询，为提供同一个表根据不同的默认条件获取不同意义的数据
    default_filters = None # {}
    # 设置request.GET中的key
    request_key = None # []

    def get_context_data(self, **kwargs):
        class OwnerModelForm(forms.ModelForm):
            class Meta:
                model = self.model_class
                fields = self.form_fields

        form_class = OwnerModelForm

        # 得到子类的类属性值
        for attr in dir(OwnerList):
            if getattr(OwnerList, attr) is None and not attr.startswith("__"):
                val_attr = getattr(self, attr)
                setattr(self, attr, val_attr)

        context = super(OwnerList, self).get_context_data(**kwargs)
        if self.form_fields:
            # 使用form作为筛选条件，搜索结果页默认选中
            set_dict_val = dict()
            for field in self.form_fields:
                if field in self.request.GET:
                    search_form_field_val = self.request.GET.get(field)
                    set_dict_val[field] = search_form_field_val

            context['form_class'] = form_class
            if set_dict_val:
                context['form_class'] = form_class(data=set_dict_val)

        # 每个页面使用变量，如果未传入会出现找不到此变量，需要设置默认
        if self.request_key:
            request_key_dict = dict.fromkeys(self.request_key, "")
            context.update(request_key_dict)
        return context

    def get_queryset(self):
        # 默认按照创建订单时间倒序
        order_fields = self.request.GET.getlist("order_fields", self.default_order_sort_field)

        # 得到time
        start_time = self.request.GET.get("start_time", None)
        end_time = self.request.GET.get("end_time", None)

        # 排除值为空的key-value, 排除无效属性key-val
        _items = {key: val for key, val in self.request.GET.items() if val and key in dir(self.model_class)}
        _items.pop("order_fields", None)
        # 加入关键字, 使用or关键字
        keywords = self.request.GET.get("keywords", None)
        args = []
        if keywords and self.search_fields:
            search_dict = dict().fromkeys(self.search_fields, keywords)
            q_filter = [Q(**{key: keywords}) for key in self.search_fields if key]
            q_search = reduce(operator.or_, q_filter)
            args.append(q_search)

        # 根据时间筛选
        is_multi_datetime_field = 1 if len(self.datetime_fields) > 1 else 0
        
        if is_multi_datetime_field:
            pass
        else: # 单个时间字段开始，结束
            if start_time and end_time:
                filter_field_operator = "".join([self.datetime_fields[0], "__", "range"])
                datetime_dict = {filter_field_operator: [start_time, end_time]}
            elif start_time:
                filter_field_operator = "".join([self.datetime_fields[0], "__", "gte"])
                datetime_dict = {filter_field_operator: start_time}
            elif end_time:
                filter_field_operator = "".join([self.datetime_fields[0], "__", "lte"])
                datetime_dict = {filter_field_operator: end_time}
            else:
                datetime_dict = {}
            args.append(Q(**datetime_dict))

        filter_fields = _items
        # 默认查询，为提供同一个表根据不同的默认条件获取不同意义的数据
        if self.default_filters:    
            filter_fields.update(self.default_filters)
        object_list = self.model_class.objects.filter(*args, **filter_fields).order_by(*order_fields)
        return object_list

live/base/templates/include/assets.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>后台管理系统-HTML5后台管理系统</title>
<meta name="keywords"  content="设置关键词..." />
<meta name="description" content="设置描述..." />
<meta name="author" content="DeathGhost" />
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
<link rel="icon" href="images/icon/favicon.ico" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<script src="{% static 'javascript/jquery.js' %}"></script>
<script src="{% static 'javascript/plug-ins/customScrollbar.min.js' %}"></script>
<script src="{% static 'javascript/plug-ins/echarts.min.js' %}"></script>
<script src="{% static 'javascript/plug-ins/layerUi/layer.js' %}"></script>
<script src="{% static 'editor/ueditor.config.js' %}"></script>
<script src="{% static 'editor/ueditor.all.js' %}"></script>
<script src="{% static 'javascript/plug-ins/pagination.js' %}"></script>
<script src="{% static 'javascript/public.js' %}"></script>
</head>
<body>
<div class="main-wrap">
    <div class="side-nav">
        <div class="side-logo">
            <div class="logo">
                <span class="logo-ico">
                    <i class="i-l-1"></i>
                    <i class="i-l-2"></i>
                    <i class="i-l-3"></i>
                </span>
                <strong>模块化后台管理模板</strong>
            </div>
        </div>
        
        <nav class="side-menu content mCustomScrollbar" data-mcs-theme="minimal-dark">
            <h2>
                <a href="index.html" class="InitialPage"><i class="icon-dashboard"></i>数据概况</a>
            </h2>
            <ul>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-columns"></i>讲师管理<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="{% url 'anchor:anchor_list' %}">讲师管理</a>
                        </dd>
                        <dd>
                            <a href="{% url 'anchor:anchor_add' %}">增加讲师</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-columns"></i>课程管理<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="{% url 'course:course_list' %}">课程管理</a>
                        </dd>
                        <!-- <dd>
                            <a href="{% url 'anchor:anchor_add' %}">增加讲师</a>
                        </dd> -->
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-columns"></i>分类管理<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="{% url 'category:category_list' %}">分类管理</a>
                        </dd>
                        <!-- <dd>
                            <a href="{% url 'anchor:anchor_add' %}">增加讲师</a>
                        </dd> -->
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-columns"></i>后台用户管理<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="{% url 'management:management_list' %}">后台用户管理</a>
                        </dd>
                    </dl>
                </li>
                <!-- <li>
                    <dl>
                        <dt>
                            <i class="icon-inbox"></i>按钮UI<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="button.html">基础按钮</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-table"></i>表格UI<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="table.html">基础表格</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-list-alt"></i>表单UI<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="form.html">表单结构样式</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-external-link"></i>弹出窗口<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="popups.html">基础弹出层</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-bar-chart"></i>百度统计echarts图表<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="echarts.html">echarts统计图表</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-font"></i>文本编辑器<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="ueditor.html">百度UEDITOR编辑器</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-road"></i>进度条<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="progress.html">progress进度条兼容</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-tags"></i>Tab选项卡<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="tab.html">Tab选项卡</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-filter"></i>下拉菜单<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="button-dropdown.html">按钮式下拉菜单</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-sitemap"></i>页面分组标题<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="title.html">页面标题</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-columns"></i>分页<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="paging.html">jquery分页效果</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-spinner"></i>旋转动画<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="animation.html">刷新加载动画</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-fighter-jet"></i>面包屑导航<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="breadcrumb.html">面包屑</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-laptop"></i>文本面板<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="text-panel.html">文本面板</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-leaf"></i>块引用<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="blockquote.html">块引用</a>
                        </dd>
                    </dl>
                </li>
                <li>
                    <dl>
                        <dt>
                            <i class="icon-star"></i>第三方弹窗组件<i class="icon-angle-right"></i>
                        </dt>
                        <dd>
                            <a href="layer.html">web弹层组件</a>
                        </dd>
                    </dl>
                </li>
            </ul> -->
        </nav>
        
        <footer class="side-footer">© DeathGhost 版权所有</footer>
        
    </div>
    <div class="content-wrap">
        <header class="top-hd">
            <div class="hd-lt">
                <a class="icon-reorder"></a>
            </div>
            <div class="hd-rt">
                <ul>
                    <li>
                        <a href="#" target="_blank"><i class="icon-home"></i>前台访问</a>
                    </li>
                    
                    <li>
                        <a><i class="icon-user"></i>管理员:<em>{{user.name}}</em></a>
                    </li>
                    
                    <li>
                        <a href="{% url 'management:logout' %}"><i class="icon-signout"></i>安全退出</a>
                    </li>
                </ul>
            </div>
        </header>
        {% block main %}
        {% endblock %}
        <footer class="btm-ft">
            <p class="clear">
                <span class="fl">©Copyright 20117 <a href="#" title="DeathGhost" target="_blank">haolei.cn</a></span>
                <span class="fr text-info">
               
                   
                    <a onclick="reciprocate()" class="text-primary"><i class="icon-qrcode"></i>捐赠</a>
                </span>
            </p>
        </footer>
    </div>
</div>
{% block js %}

{% endblock %}
</body>
</html>

live/base/templates/include/pagination.html
<!-- <div id="pagenavi" class="noselect" style="width:{{page_tag_num}}px; margin: 0 auto; display: block"> -->
<div id="pagenavi" class="noselect" style=" display: block">
    {% if first_page == current_page %}
        <li class="active"><a><span class="first-page current">1</span></a></li>
    {% else %}
        <li><a href="?page=1{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&{{ key }}={{ value }}{% endifnotequal %}{% endfor %}" class="first-page">1</a></li>
    {% endif %}

    {% if pages_first > 2 %}
        <li><a><span>...</span></a></li>
    {% endif %}
    {% for page in pages %}
        {% if page == current_page %}
            <li class="active"><a><span class="current">{{ page }}</span></a></li>
        {% else %}
            <li><a href="?page={{ page }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">{{ page }}</a></li>
        {% endif %}
    {% endfor %}
    {% if pages_last < last_page %}
        <li><a><span>...</span></a></li>
    {% endif %}

    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <li class="active"><a><span class="current">{{ last_page }}</span></a></li>
        {% else %}
            <li><a href="?page={{ last_page }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">{{ last_page }}</a></li>
        {% endif %}
    {% endif %}
    <div class="clearfix"></div>
</div>