live/audience/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from . import views



urlpatterns = [
    url(r'^login/$', views.UserInfoLogin.as_view(), name='login'),
    url(r'^register/$', views.Registration.as_view(), name='register'),  # 注册
    url(r'^get_verification_code/$', views.VerificationCodeView.as_view()),  # 获取验证码
    url(r'^reset_password/$', views.ResetPasswordView.as_view(), name='reset_password'),  # 修改密码




]

live/live/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^anchor/', include('anchor.urls', namespace="anchor")),
    url(r'^course/', include('course.urls', namespace="course")),
    url(r'^category/', include('category.urls', namespace="category")),
    url(r'^audience/', include('audience.urls', namespace="audience")),
    url(r'^management/', include('management.urls', namespace="management")),
    url(r'^index/', include('index.urls', namespace="index")),




    #直播api
    url(r'^courses/', include('course.api_urls')),
    url(r'^categories/', include('category.api_urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

live/audience/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

class UserInfo(models.Model):

    owner = models.OneToOneField(User, related_name='owner', null=True)
    user_id = models.CharField(max_length=100, unique=True, null=True)

    name = models.CharField(max_length=30, verbose_name=u'姓名', default='')
    
    sex = models.IntegerField(default=1, choices=((1, u'男'), (0, u'女')))
    age = models.IntegerField(null=True, default=30, blank=True)
    tel = models.CharField(max_length=50, null=True, unique=True)
    passwd = models.CharField(max_length=100, default='', null=True)
    e_mail = models.CharField(max_length=50, null=True, default='')
    title = models.TextField(verbose_name=u'头衔', null=True, default='')
    image = models.ImageField(upload_to='images/user_info/', null=True)
    create_time = models.DateTimeField(auto_now_add=True, null=True)
    type =models.IntegerField(default=2, choices=((2, u'普通用户'), (1, u'管理员')))

    
    @property
    def get_sex(self):
        gender = u"女"
        if self.sex == 1:
            gender = u"男"
        return gender

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'user_info'

live/audience/views.py
# -*- coding: utf-8 -*-
import requests
import datetime
import hashlib
import uuid
import urllib
import json
import operator
from functools import reduce
import logging

from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.views.generic import ListView, CreateView, FormView, TemplateView, DetailView, View
from django.conf import settings
from django.http import JsonResponse, HttpResponse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib import messages
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from django.db import transaction

from models import UserInfo
from utils import get_unique_username
from sdk.xxx import VerificationCode


# 1 注册 2 手机登录 3 第三方绑定 4 修改密码 5 修改手机号码
CODE_REGISTRATION = '1'
CODE_LOGIN = '2'
CODE_BIND = '3'
CODE_RESET_PASSWORD = '4'
CODE_RESET_PHONE = '5'

# @method_decorator(login_required, name='dispatch')
# # @method_decorator(user_group_required('admin,staff'), name='dispatch')
# class Index(ListView):
#     '''
#     前端用户首页
#     '''
#     template_name = 'user/user_table.html'
#     # paginate_by = PAGE_NUM
#     context_object_name = 'obj_list'

#     def get_context_data(self, **kwargs):
#         context = super(Index, self).get_context_data(**kwargs)
#         context['PRIMARY_ACCOUNT_TYPE'] = settings.PRIMARY_ACCOUNT_TYPE # accountType__name
#         return context

#     def get_queryset(self):
#         during_dict = {'day': u'一天', 'week': u'一周', 'month': u'一月', 'forever': u'永久'}
#         users = UserInfo.objects.filter(type=2).order_by('-create_time')  # 类型为２的才是用户
#         for user in users:
#             ban_statue = u'正常'
#             if user.ban == 2:
#                 diff = (user.ban_time - datetime.datetime.now())
#                 if diff.seconds > 0:
#                     ban_statue = u'禁言(' + during_dict[user.ban_during] + '）'
#                 else:
#                     user.ban = 1
#                     user.save()
#             elif user.ban == 3:
#                 ban_statue = u'封禁'
#             user.ban_statue = ban_statue
#         return users



class UserInfoLogin(TemplateView):
    '''
    前端用户登录
    '''
    template_name = 'audience/login.html'

    def get_context_data(self, **kwargs):
        context = super(UserInfoLogin, self).get_context_data(**kwargs)
        context['next'] = ''
        next = self.request.GET.get('next')
        if next:
            context['next'] = next
        return context

    def post(self, request):
        try:
            phone = request.POST.get('phone')
            password = request.POST.get('password')
            code = request.POST.get('code')
            next = request.POST.get('next', None)

            user = authenticate(username=phone, password=password)
            if not user:
                # user 登录不成功，则换userinfo进行登录
                user_info_list = UserInfo.objects.filter(tel=phone)
                if not user_info_list:
                    messages.error(request, u'用户不存在')
                    return redirect('audience:login')

                user_info = user_info_list.first()
                if not code:
                    # 通过 手机 + 密码登录
                    if not check_password(password, user_info.passwd):
                        # 如果该方式检测不能成功登录，则使用自定义加密方式进行验证
                        password = user_info.user_id + settings.SECRET_KEY + password
                        password = hashlib.new('md5', password.encode("utf8")).hexdigest()
                        if password != user_info.passwd:
                            messages.error(request, u'用户名密码不匹配')
                            return redirect('audience:login')
                else:
                    # 通过 手机 + 验证码登录
                    memory_code = VerificationCode.get_code_by_phone(phone)
                    if memory_code != code:
                        messages.error(request, u'验证码不对')
                        return redirect('audience:login')
                user = user_info.owner

            # 判断完条件 则登录
            login(self.request, user)

            response = redirect('anchor:anchor_list')
            print next
            if next:
                response = redirect(next)
            return response

        except Exception as e:
            print str(e)
            return render(request, 'audience/login.html')


class ResetPasswordView(View):
    '''
    重置密码
    '''

    def post(self, request):
        phone = request.POST.get('phone')
        password = request.POST.get('password')
        code = request.POST.get('code')

        memory_code = VerificationCode.get_code_by_phone(phone)
        if memory_code != code:
            messages.error(request, u'验证码错误')
            return redirect('audience:login')

        user_info_list = UserInfo.objects.filter(tel=phone)
        if not user_info_list:
            messages.error(request, u'用户名不存在')
            return redirect('audience:login')

        user_info = user_info_list.first()
        user_info.passwd = make_password(password)
        user_info.save()

        # 更改完密码后直接登录
        user = user_info.owner
        login(self.request, user)

        response = redirect('anchor:anchor_list')
        return response


class VerificationCodeView(View):
    '''
    获取验证码
    '''

    def get(self, request, **kwargs):
        '''
        获取验证码

        1 注册 2 手机登录 3 第三方绑定 4 修改密码 5 修改手机号码
        CODE_REGISTRATION = '1'
        CODE_LOGIN = '2'
        CODE_BIND = '3'
        CODE_RESET_PASSWORD = '4'
        CODE_RESET_PHONE = '5'

        :param request:
        :return:
        '''
        phone = request.GET.get('phone', None)
        operate = request.GET.get('operate', CODE_REGISTRATION)
        user_info = UserInfo.objects.filter(tel=phone)

        # TODO 业务逻辑不清晰，待完善
        if operate == CODE_REGISTRATION:
            #  注册用户 获取验证码
            if user_info:
                return HttpResponse('该用户已存在', status=409)

        if operate in [CODE_LOGIN, CODE_RESET_PASSWORD]:
            # 已注册用户获取验证码
            if not user_info:
                return HttpResponse('用户不存在', status=404)

        result, code = VerificationCode.send_verification_code(phone)
        data = eval(result.text)
        if '25010' == data.get('code'):
            VerificationCode.save(phone, code)
            return HttpResponse(code, status=200)
        return HttpResponse('发送验证码失败，请稍后再试，谢谢！', status=500)


class Registration(View):
    '''
    注册

    检测手机号是否重复，但是检测为空的情况

    采用django 默认的加密方式

    user_info 需要存 user_id 字段，兼容老功能
    '''

    def post(self, request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        password = request.POST.get('password')
        code = request.POST.get('code')

        # 匹配验证码
        memory_code = VerificationCode.get_code_by_phone(phone)
        if memory_code != code:
            messages.error(request, '验证码错误')
            return redirect('audience:login')

        # 检测手机号
        if not phone:
            messages.error(request, '请输入手机号')
            return redirect('audience:login')

        user_info_list = UserInfo.objects.filter(tel=phone)
        if user_info_list:
            messages.error(request, '号码已经被注册使用')
            return redirect('audience:login')

        username = get_unique_username()
        with transaction.atomic():
            user = User.objects.create_user(username=username)
            owner = UserInfo(owner=user,  user_id=str(uuid.uuid1()).replace('-', ''), tel=phone, name=name, passwd=make_password(password))
            owner.save()

            login(self.request, user)

        response = redirect('anchor:anchor_list')
        return response

live/audience/templates/audience/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/html">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="Shortcut Icon" href="">
    <title>有获网络</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <link rel='stylesheet' id='amazeui-css' href="{% static 'css/bootstrap.css' %}" type='text/css' media='all'/>

    <link rel='stylesheet' id='msite-css' href="{% static 'user/css/login.css' %}" type='text/css' media='all'/>

    {#  因为模态框, 所以引入site.css文件  #}
    <link rel="stylesheet" href="{% static 'user/css/login_msite.css' %}">
    <script type='text/javascript' src="{% static 'js/jquery-3.0.0.js' %}"></script>
</head>

<body style="background:#f6f6f6;">


<!-- 手机验证登录 -->
<div class="md_content unable_Login_useVcode">
    <div class="back-delect_main_Div">
        <div class="fl unable_Login_useVcode_back"><img src="{% static 'images/arrow_left.png' %}" width="26"></div>
        <div class="fr unable_Login_useVcode_close"><img src="{% static 'images/arrow_delect.png' %}" width="26"></div>
    </div>
    <div class="cutbox_10px"></div>
    <div class="textAlign_C">
        <h3 class="main-color_666">手机验证登录</h3></div>
    <div class="main-color_999 textAlign_C">验证码将会发送至你的手机</div>
    <div class="cutbox_20px"></div>
    <form method="post" action="{% url 'audience:login' %}">
        {% csrf_token %}
        <div class="unable_Login_resetPw_groupInputs group-inputs">
            <div class="mobil input-wrapper">
                <input class="login-phone" name="phone" aria-label="手机号（ 仅支持中国大陆 ）" placeholder="手机号（ 仅支持中国大陆 ）">
                <label class="error">请输入手机号</label>
            </div>
            <div class="vcode input-wrapper topRadius_0">
                <div class="getVcode">
                    <input class="login-code-btn" type="button" value="获取验证码">
                </div>
                <input name="code" type="text" aria-label="六位验证码" placeholder="六位验证码">
                <label class="error">请输入验证码</label>
            </div>
        </div>
        <div class="cutbox_20px"></div>

        <div class="unable_login_btn submit">
            <button type="submit" class="sign-button submit_signIn submit">
                登录
            </button>

            {% if messages %}
                {% for message in messages %}
                    <div class="panel panel-danger layer_abso">
                        <div class="panel-heading"><h3 class="panel-title">{{ message }}</h3></div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </form>
</div>


<!-- 无法登录弹窗 -->
<div class="md_content unable_Login">
    <div class="back-delect_main_Div">
        <div class="fl"></div>
        <div class="fr unable_Login_close"><img src="{% static 'images/arrow_delect.png' %}" width="26"></div>
    </div>
    <div class="cutbox_10px"></div>
    <div class="textAlign_C">
        <h3 class="main-color_666">无法登录</h3></div>
    <div class="main-color_999 textAlign_C">我们有两种方式帮助你重新登录有获</div>
    <div class="cutbox_20px"></div>
    <div class="unable_login_btn unable_login_resetPw_btn">重设密码</div>
    <div class="cutbox_20px"></div>
    <div class="unable_login_btn unable_login_useVcode_btn">使用手机验证码登录</div>
</div>


<!-- 重设密码 -->
<div class="md_content unable_Login_resetPw">
    <div class="back-delect_main_Div">
        <div class="fl unable_Login_resetPw_back"><img src="{% static 'images/arrow_left.png' %}" width="26"></div>
        <div class="fr unable_Login_resetPw_close"><img src="{% static 'images/arrow_delect.png' %}" width="26"></div>
    </div>
    <div class="cutbox_10px"></div>
    <div class="textAlign_C">
        <h3 class="main-color_666">重设密码</h3></div>
    <div class="main-color_999 textAlign_C">验证码将会发送至你的手机</div>
    <div class="cutbox_20px"></div>
    <form method="post" action="{% url 'audience:reset_password' %}">
        {% csrf_token %}
        <div class="unable_Login_resetPw_groupInputs group-inputs">
            <div class="mobil input-wrapper">
                <input class="reset-phone" name="phone" aria-label="手机号（ 仅支持中国大陆 ）" placeholder="手机号（ 仅支持中国大陆 ）">
                <label class="error">请输入手机号</label>
            </div>
            <div class="vcode input-wrapper topRadius_0">
                <div class="getVcode">
                    <input class="reset-code-btn" type="button" name="modifysend" value="获取验证码">
                </div>
                <input name="code" type="text" aria-label="六位验证码" placeholder="六位验证码">
                <label class="error">请输入验证码</label>
            </div>
            <div class="password input-wrapper">
                <input name='password' type="password" aria-label="密码（ 不少于6位 ）" placeholder="密码（ 不少于6位 ）">
                <label class="error">请输入密码</label>
            </div>
        </div>
        <div class="cutbox_20px"></div>

        <div class="unable_login_btn submit">
            <button type="submit" class="sign-button submit_signIn submit">
                重设密码
            </button>

            {% if messages %}
                {% for message in messages %}
                    <div class="panel panel-danger layer_abso">
                        <div class="panel-heading"><h3 class="panel-title">{{ message }}</h3></div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </form>
</div>


 
<!-- 首页 包含 登录 注册-->
<header class="tm-header" style="min-width:290px; min-height:428px; ">
    <div class="tm-header-inner">
        <div class="tm-header-content">
            <div class="tm-logo">
                <div class="margin_Auto">有获</div>
            </div>
            <div class="cutbox_20px">

            </div>
            <h2 class="subtitle">有获，让更多智慧高效助力更多企业成长</h2>
            <div class="cutbox_20px"></div>

            <div class="index-tab-navs">
                <div class="navs-slider">
                    <a class="navs-slider-btn active" href="#signup" data-i="1">登录</a>
                    <a class="navs-slider-btn" href="#signin" data-i="2">注册</a>
                    <span class="navs-slider-bar"></span>
                </div>
                <div class="cutbox_30px"></div>
            </div>

            <div class="loginIn active">
                <form method="post" action="{% url 'audience:login' %}">
                    {% csrf_token %}
                    <div class="view signIn" style="display:block;">
                        <input type="hidden" name="next" value="{{ next }}">
                        <div class="group-inputs">
                            <div class="mobil input-wrapper">
                                <input type="text" name="phone" aria-label="手机号" placeholder="手机号">
                                <label class="error">输入手机号</label>


                            </div>
                            <div class="password input-wrapper" style="border-top:1px solid #ddd;">
                                <input name="password" type="password" aria-label="密码" placeholder="密码">
                                <label class="error">请输入密码</label>
                            </div>
                        </div>
                    </div>

                
                    <div class="cutbox_10px"></div>
                    <div class="button-wrapper command marg-top-20px">
                        <button type="submit" class="sign-button submit_signIn submit">
                            登录
                        </button>

                        {% if messages %}
                            {% for message in messages %}
                                <div class="panel panel-danger layer_abso">
                                    <div class="panel-heading"><h3 class="panel-title">{{ message }}</h3></div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>


                </form>

                <div class="signin-misc-wrapper clearfix">
                    <div class="checkbox margin_Auto">
                        <label class="remember-me">
                            <input type="checkbox" checked> 记住我
                        </label>
                        <label class="canot-sign">
                            <a class="unable-login fr" style="color:#489a5b" href="javascript:void(0)">无法登录？</a>
                        </label>
                    </div>
                </div>
            </div>


            <div class="loginUp">
                <form method="post" action="{% url 'audience:register' %}">
                    {% csrf_token %}
                    <div class="view signIn">
                        <div class="group-inputs">
                            <div class="mobil input-wrapper">
                                <input name="name" aria-label="姓名" placeholder="姓名">
                                <label class="error">输入姓名</label>
                            </div>
                            <div class="mobil input-wrapper topRadius_0">
                                <input name="phone" class="register-phone" placeholder="手机号（ 仅支持中国大陆 ）">
                                <label class="error">请输入手机号</label>
                            </div>
                            <div class="vcode input-wrapper topRadius_0">
                                <div class="getVcode">
                                    <input class="register-code-btn" type="button" value="获取验证码">
                                </div>
                                <input name="code" aria-label="六位验证码" placeholder="六位验证码">
                                <label class="error">请输入验证码</label>
                            </div>
                            <div class="password input-wrapper">
                                <input type="password" name="password" placeholder="密码（ 不少于6位 ）">
                                <label class="error">请输入密码</label>
                            </div>
                        </div>
                        <div class="weibo-signup-wrapper margin_Auto">
                            <label class="weiboSignUp assit-color">&nbsp;&nbsp;注：中文或者英文字符，不得超过20个字符</label>
                        </div>
                    </div>
                    <div class="cutbox_10px"></div>
                    <div class="button-wrapper command">
                        <button class="sign-button submit_signIn submit" type="submit">注册</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>

</header>
<script type="text/javascript" src="/static/user/js/login.js"></script>


</body>

</html>