live/course/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include

from . import  views

urlpatterns = [
    # 前端用户
    url(r'^course_list/$', views.CourseList.as_view(), name='course_list'),
    url(r'^course_add/$', views.CourseAdd.as_view(), name='course_add'),
    url(r'^course_edit/(?P<pk>\w*)/$', views.CourseEdit.as_view(), name='course_edit'),
    url(r'^course_audit/$', views.audit, name='course_audit'),

  	#直播地址
    url(r'^live_room/(?P<pk>\w*)/$', views.LiveRoom.as_view(), name='live_room'),

]

live/live/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^anchor/', include('anchor.urls', namespace="anchor")),
    url(r'^course/', include('course.urls', namespace="course")),
    url(r'^category/', include('category.urls', namespace="category")),
    url(r'^audience/', include('audience.urls', namespace="audience")),
    url(r'^management/', include('management.urls', namespace="management")),
    url(r'^index/', include('index.urls', namespace="index")),




    #直播api
    url(r'^courses/', include('course.api_urls')),
    url(r'^categories/', include('category.api_urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

live/course/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from anchor.models import AnchorInfo
from category.models import Category
import enum


# 课程状态
COURSE_LIVE = 1  # 直播
COURSE_RESERVATION = 2  # 预订
COURSE_OVER = 3  # 直播结束
COURSE_REPLAY = 4  # 录播
COURSE_VALIDATE = 5  # 直播待审核状态
COURSE_INVALID = 6  # 直播审核不通过
COURSE_INVALID_7 = 7  # 录播审核不通过
COURSE_INVALID_8 = 8  # 录播待审核状态
COURSE_LIVE_NOUSER = 9  # 正在直播，主播不在

LIVE_STATUS_OVER = 'live_over'
LIVE_STATUS_ON = 'live_on'
LIVE_STATUS_CHOICES = ((LIVE_STATUS_ON, '正在直播'), (LIVE_STATUS_OVER, '直播结束'))

RECORD_STATUS_NO = 'record_no'
RECORD_STATUS_HAVE = 'record_have'


RECORD_STATUS_CHOICES = ((RECORD_STATUS_NO, '不生成录播'), (RECORD_STATUS_HAVE, '生成录播'))

RESOURCE_LOCAL = '3'  # 本地资源
RESOURCE_THIRD = '2'  # 第三方资源
RESOURCE_ULLGET = '1'  # ullget
RESOURCE_STATUS_CHOICES = ((RESOURCE_ULLGET, 'ullget'), (RESOURCE_THIRD, '第三方资源'),
                           (RESOURCE_LOCAL, '本地资源'))

@enum.unique
class RECORD(enum.IntEnum):
    RECORD_ON = 1
    RECORD_OFF = 2

# Create your models here.
class CourseInfo(models.Model):
    """
    课程# 课程直播状态
    """

    course_id = models.CharField(u'课程id', max_length=100, unique=True, null=True)
    title = models.CharField(u'课程标题', max_length=100, help_text=u'不得超过100字符!', null=True)
    description = models.TextField(u'课程简介')

    anchor = models.ForeignKey(AnchorInfo, null=True, related_name="anchor_course")
    support = models.IntegerField(u'点赞', default=0)
    against = models.IntegerField(u'踩', default=0)

    start_time = models.DateTimeField(u'直播开始时间', null=True, auto_now_add=False)
    end_time = models.DateTimeField(u'直播结束时间', null=True)
    create_time = models.DateTimeField(u'创建时间', null=True, auto_now_add=True)

    up_time = models.DateTimeField(u'更新时间', null=True, auto_now=True)
    image = models.ImageField(upload_to='images/course/', null=True)
    status = models.SmallIntegerField(u'直播状态', default=0)
  
    audit = models.IntegerField(default=5, verbose_name=u'审计状态')  
    reason = models.CharField(u"不通过原因", max_length=200, null=True)
    category = models.ForeignKey(Category, null=True)

    sign_num = models.IntegerField(default=0, verbose_name=u'初识报名人数') 
    url = models.CharField(u"地址", max_length=500, null=True)
    active = models.IntegerField("激活", default=1)  # 1-显示  2-隐藏  3-删除
    live_to_record = models.IntegerField(choices=((x.value, x.name.title()) for x in RECORD),
                                         default=RECORD.RECORD_ON.value)

    class Meta:
        db_table = 'course_info'




class Channel(models.Model):
    '''
    视频推流拉流，推流表 基表
    '''
    pulish_url = models.CharField(u"直播rtmp推流", max_length=500, null=True)
    url_rtmp = models.CharField(u"直播rtmp格式拉流地址", max_length=500, null=True)
    url_flv = models.CharField(u"直播flv格式拉流地址", max_length=500, null=True)
    url_hls = models.CharField(u"直播htls拉流地址", max_length=500, null=True)
    appname = models.CharField(u'appname', max_length=100, null=True, help_text='用企业号去表示')
    stream_name = models.CharField(u'stream_name', max_length=100, null=True, help_text='课程号表示')
    status = models.CharField(max_length=20,
                              choices=LIVE_STATUS_CHOICES,
                              default=LIVE_STATUS_ON)
    record_status = models.CharField(max_length=20,
                                     choices=RECORD_STATUS_CHOICES,
                                     default=RECORD_STATUS_NO, help_text='是否生成录播')
    notify_message = models.CharField(max_length=100, null=True, help_text='录播状态描述')
    create_time = models.DateTimeField(u'创建时间', null=True, auto_now_add=True)

    class Meta:
        db_table = "channel_info"


class LiveChannel(models.Model):
    '''
    视频与视频流的中间表
    '''
    # 直播流当前状态, 默认为测试
    STREAM_STATUS_TEST = "test"
    STREAM_STATUS_NORMAL = "normal"
    STREAM_STATUS_CHOICE = (
        (STREAM_STATUS_TEST, "test stream"),
        (STREAM_STATUS_NORMAL, "normal stream")
    )
    video = models.ForeignKey(CourseInfo, 'course_id', null=True, related_name="video_channel")
    channel = models.ForeignKey(Channel, null=True, related_name="live_channel")
    status = models.CharField(max_length=20,
                              choices=LIVE_STATUS_CHOICES,
                              default=LIVE_STATUS_ON)
    notify_message = models.CharField(max_length=100, null=True, help_text='录播状态描述')
    stream_name = models.CharField(max_length=100, null=True, help_text='创建流的三级名')
    create_time = models.DateTimeField(u'创建时间', null=True, auto_now_add=True)
    stream_status = models.CharField(max_length=30, choices=STREAM_STATUS_CHOICE, default=STREAM_STATUS_CHOICE[0][0])

    class Meta:
        db_table = "live_channel"

live/course/views.py
# -*- coding: utf-8 -*-
import os
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# from base.views import OwnerList
from .models import CourseInfo, LiveChannel, Channel
from anchor.models import AnchorInfo
from category.models import Category
from .utils import get_uuid

@method_decorator(login_required, name='dispatch')
class CourseList(generic.ListView):
    template_name = 'course/course_list.html'
    context_object_name = 'obj_list'

    def get_queryset(self):
        title = self.request.GET.get('title')
        if title:
            object_list = CourseInfo.objects.filter(title__icontains=title)  
        else:
            object_list = CourseInfo.objects.all()
        return object_list


@method_decorator(login_required, name='dispatch')
class CourseAdd(generic.TemplateView):
    template_name = "course/course_add.html"

    def get_context_data(self, **kwargs):
        context = super(CourseAdd, self).get_context_data(**kwargs)
        context['user'] = AnchorInfo.objects.all()
        context['categories'] = Category.objects.all()
        return context

    def post(self, request):
        post_data = request.POST
        post_file = request.FILES
        image = post_file.get('image', None)
        if image:
            post_data.update({'image': image})
        else:
            post_data.pop('image')
        post_data.update({'course_id':get_uuid()})
        save_data = {key: val for key, val in post_data.items() if val and key in dir(CourseInfo)}
        anchor_info = CourseInfo(**save_data)
        anchor_info.save()
        return redirect("course:course_list")

@method_decorator(login_required, name='dispatch')
class CourseEdit(generic.DetailView):
    template_name = "course/course_add.html"
    model = CourseInfo
    queryset = CourseInfo.objects.all()

    def get_context_data(self, **kwargs):
        '''
        方便以后添加其他信息
        '''
        context = super(CourseEdit, self).get_context_data(**kwargs)
        context['user'] = AnchorInfo.objects.all()
        context['categories'] = Category.objects.all()
        
        return context

    def get(self, request, pk):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['object'] = self.object
        context['action'] = "/course/course_edit/{}/".format(pk)
        return self.render_to_response(context)

    def post(self, request, pk):
        post_data = request.POST
        post_file = request.FILES
        image = post_file.get('image', None)
        if image:
            post_data.update({'image': image})
        course = CourseInfo.objects.get(pk=pk)

        for key, val in post_data.items():
            if not val:
                post_data.pop(key)
                continue
            if hasattr(course, key):
                setattr(course, key, val)
        course.save()
        return redirect("course:course_list")

@csrf_exempt
def audit(req):
    post_data = req.POST
    audit = post_data.get('audit', None)
    id = post_data.get('id', None)
    course = CourseInfo.objects.get(pk=id)
    course.audit = audit
    course.save()
    return JsonResponse({'result': 'success', 'message': u'修改成功'})



@method_decorator(login_required, name='dispatch')
class LiveRoom(generic.DetailView):
    template_name = "course/live_room.html"
    context_object_name = "object"
    model = CourseInfo

    def get_context_data(self, **kwargs):
        '''
        方便以后添加其他信息
        '''
        context = super(LiveRoom, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def get(self, request, pk):
        self.object = self.get_object()
        print self.object,'======'
        context = self.get_context_data(object=self.object)
        context['object'] = self.object
        course_id=self.object.course_id
        #扩展点赞
        # context['support'] =support    
        channel_url = {'url_rtmp': '', 'url_flv': '', 'url_hls': '', 'pulish_url': '', 'status': ''}
        context['channel_url'] = channel_url
        live_channel = LiveChannel.objects.filter(video_id=course_id).first()
        if not live_channel:
            return context
        channel_info = Channel.objects.filter(pk=live_channel.channel_id).first()
        channel_url['url_rtmp'] = channel_info.url_rtmp
        channel_url['url_flv'] = channel_info.url_flv
        channel_url['url_hls'] = channel_info.url_hls
        channel_url['publish_url'] = channel_info.pulish_url
        channel_url['status'] = channel_info.status  
        print(channel_url,'=======') 
        return self.render_to_response(context)
 

   

live/course/templates/course/course_add.html
{% extends "include/assets.html" %}
{% load staticfiles %}

{% block main%}
    <main class="main-cont content mCustomScrollbar">
            <div class="page-wrap">
                <!--开始::内容-->
               <div class="panel-body">
                    <section id="unseen">
                        <div>
                            <form action="{% if action %}{{ action }}{% else %}{% url 'course:course_add' %}{%endif%}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                        
                                <div class="form-group-col-2">
                                    <div class="form-label">标题：</div>
                                    <div class="form-cont">
                                        <input type="text"  name="title" value="{{ object.title }}" class="form-control form-boxed" style="width:300px;">
                                    </div>
                                </div>
                                
                                <div class="form-group-col-2">
                                    <div class="form-label">讲师：</div>
                                    <div class="form-cont">
                                        <select name="anchor_id" class="form-control" style="width:300px;">
                                        {% for star in user %}

                                            <option value="{{ star.id }}" {%if object.anchor_id == star.id%}selected="selected"{%endif%}>{{ star.name }}</option>
                                        {% endfor %}
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group-col-2">
                                    <div class="form-label">基础报名人数</div>
                                    <div class="form-cont">
                                        <input type="text" name="sign_num"  value="{{ object.sign_num }}" class="form-control form-boxed" style="width:300px;">
                                    </div>
                                </div>

                                <div class="form-group-col-2">
                                    <div class="form-label">分类领域</div>
                                    <div class="form-cont">
                                       <select name="category_id" class="form-control" style="width:300px;">
                                        {% for category in categories %}
                                            <option {%if object.category_id == category.id%}selected="selected"{%endif%} value="{{ category.id }}">{{ category.name }}</option>
                                        {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group-col-2">
                                    <div class="form-label">描述</div>
                                    <div class="form-cont">
                                            <textarea  name="description" class="form-control" style="width:300px;">{{ object.description }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group-col-2">
                                    <div class="form-label">图片</div>
                                    <div class="form-cont">
                                            {% if  object.image %}
                                            <img src="/media/{{object.image}}"></img>
                                            {% endif %}
                                            <input  type="file" name="image"  >
                                    </div>
                                </div>
                                <div class="form-group-col-2">
                                    <div class="form-label">时间</div>
                                    <div class="form-cont">
                                            <label for="meeting">开始时间:{{object.create_time}}</label>
                                            <input name="start_time" value="{{object.create_time}}" type="datetime-local" />
                                            <div class="form-cont"></div>
                                            <label for="meeting">结束时间:{{object.end_time}}</label><input name="end_time" value="{{object.end_time}}" 
                                            type="datetime-local" />

                                         
                                    </div>
                                </div>
                                
                            </div>
                                

                            <div class="cutbox_20px clear_Both"></div>
                            <div class="cutbox_20px clear_Both"></div>
                            <div class="clear_Both lh2em">
                            <label class="col-sm-2 tl"></label>
                            <div class="col-sm-10">
                                <button class="verify btn btn-info submit" style="padding-left: 15px; padding-right: 15px;" type="submit">保存</button>
                            </div>
                            </div>
                        </form>
                        <div class="cutbox_20px clear_Both"></div>
                        <div class="cutbox_20px clear_Both"></div>
                    </section>
                </div>
                 
                <!--开始::结束-->
            </div>
        </main>
     
{% endblock %}

live/course/templates/course/course_list.html
{% extends "include/assets.html" %}
{% block main%}
{% load request_args %}
    <main class="main-cont content mCustomScrollbar">
            <div class="page-wrap">
                <!--开始::内容-->
                <section class="page-hd">
                    <header>
                        <h2 class="title">课程管理</h2>
                        <p class="title-description">
                        <a href="{% url 'course:course_add' %}" target="_blank">创建课程</a>
                        </p>
                    </header>
                    <hr>
                </section>
                <div class="panel panel-default">
                    <section id="unseen">
                            <form action="" method="get">

                                <div class="span6">

                              
                                
                                    <div class="form-group fl">
                                        <label class="control-label fl">课程标题:&nbsp;&nbsp;</label>
                                        <div class="fl">
                                            <input type="text" name="title" class="form-control phone"
                                                   aria-controls="dynamic-table" value="{{ request.GET|ck_request_args:'title' }}">
                                        </div>
                                    </div>
                                    <!-- <div class="form-group fl">
                                        <label class="control-label fl">姓名:&nbsp;&nbsp;</label>
                                        <div class="fl">
                                            <input type="text" name="name" class="form-control name"
                                                   aria-controls="dynamic-table" value="{{ request.GET|ck_request_args:'name' }}">
                                        </div>
                                    </div> -->

                                    <div class=" fl ">
                                        <div class="fl">
                                            <button class="btn btn-info fl search-user "
                                                    style="padding-left: 15px; padding-right: 15px;"
                                                    type="submit">查找
                                            </button>
                                        </div>
                                    </div>
                                </div>

                            </form>
                            <table class="table table-bordered table-striped table-condensed">
                                <thead>
                                <tr>
                                    <th style="display: none"></th>
                                    <th class="numeric">标题</th>
                                    <th class="numeric">讲师</th>
                                    <th class="numeric">创建日期</th>
                                    <th class="numeric">点赞数</th>
                                    <th class="numeric">状态</th>
                                    <th class="numeric">操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% load paginate_tags %}
                                {% paginate obj_list 10 %}

                                {% for obj in obj_list %}
                                    <tr>
                                        <td style="display: none" class="td-id"><input name="{{ objct.id }}" class="id"/>
                                        </td>
                                        <td class="numeric">{{ obj.title }}</td>
                                        <td class="numeric">{{ obj.anchor.name }}</td>
                                        <td class="numeric">{{ obj.create_time | date:"Y-m-d H:i" }}</td>
                                        <td class="numeric ban_statue">{{obj.support}}</td>
                                        <td class="numeric ban_statue">
                                            {% if obj.audit == 1 %}
                                            上架
                                            {% else %}
                                            待上架
                                            {% endif %}                                           

                                        </td>
                                        <td class="numeric opt">
                                            <a href="/course/course_edit/{{ obj.id }}/" >编辑</a>
                                            <a href="/course/live_room/{{ obj.course_id }}/" >直播地址</a>
                                            {% if obj.audit == 1 %}
                                                <a class="charge_btn" data="{{ obj.id }}" data_value="0" >下架</a>

                                            {% else %}
                                                <a class="charge_btn" data="{{ obj.id}}" data_value="1" >上架</a>
                                            {% endif %}        

                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <div class="row-fluid">
                                <div class="span6">
                                    <div class="dataTables_info" id="dynamic-table_info">
                                    </div>
                                </div>
                                <div class="span6">
                                    <div class="dataTables_paginate paging_bootstrap pagination ">
                                        <ul>
                                            {% include 'include/pagination.html' %}
                                        </ul>

                                    </div>

                                </div>
                            </div>
                        </section>
                    </div>
                </section>
                </div>
                <!--开始::结束-->
            </div>
        </main>
     
{% endblock %}
{% block js %}
    <script type="text/javascript" src="/static/course/js/control.js"></script>
{% endblock %}

live/course/templates/course/live_room.html
<!DOCTYPE HTML>
<html lang="en-US">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{object.title}}直播间</title>
		<link rel="icon" type="image/png" href="favicon.png"> 
		<link rel="stylesheet" href="/static/course/sbtp_53_obey/css/animate.css" media="all" />            <!-- Animate css -->
		<link rel="stylesheet" href="/static/course/sbtp_53_obey/css/font-awesome.min.css" media="all" />   <!-- Font awesome css -->
        <link rel="stylesheet" href="/static/course/sbtp_53_obey/css/font-sourch_sun_pro.css"/>             <!-- Font css -->	
        <link rel="stylesheet" href="/static/course/sbtp_53_obey/fonts/comicSans.css"/> 					<!-- Font css -->
        <link rel="stylesheet" href="/static/course/sbtp_53_obey/css/slicknav.css"/>	 					<!-- Slicknav css -->
		<link rel="stylesheet" href="/static/course/sbtp_53_obey/css/bootstrap.min.css"/>  					<!-- Bootstrap -->
        <link rel="stylesheet" href="/static/course/sbtp_53_obey/css/owl.carousel.css">	   					<!-- carousel css -->
        <link rel="stylesheet" href="/static/course/sbtp_53_obey/css/owl.theme.css">   						<!-- Owl theme css -->			
		<link rel="stylesheet" href="/static/course/sbtp_53_obey/css/reset.css"/>						 	<!-- Recet css -->
		<link rel="stylesheet" href="/static/course/sbtp_53_obey/switcher/switcher.css"/>					<!-- Switcher css -->				
		<link rel="stylesheet" href="/static/course/sbtp_53_obey/css/style2.css"/>							<!-- Style css -->
		<link rel="stylesheet" href="/static/course/sbtp_53_obey/css/responsive.css" media="all" />			<!-- Responsive css -->
		<link rel="stylesheet" href="/static/course/sbtp_53_obey/css/preloder.css" media="all" />			<!-- Preloder css -->
	<!--[if lt IE 8]><link rel="stylesheet" href="assets/blueprint-css/ie.css" type="text/css" media="screen, projection"><![endif]-->

	<link href="http://vjs.zencdn.net/5.20.1/video-js.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/5.20.1/videojs-ie8.min.js"></script>
	</head>
	<body>
		<!-- loader-wrapper -->		
		
			<div class="home_area"> <!-- Home area-->
				<div class="container">
					<div class="row">
						<div class="col-sm-12">
							<div class="logo">
								<img src="img/logo.png" alt="" /> <!-- Here is your logo -->
							</div>	
						</div>
					</div>
				</div>
				<div class="container">
					<div class="row">
						<div class="col-sm-12">
							<div class="home_area_text">
								<h2 >{{object.title}}</h2> <!-- Page title -->
								<h3 id="push_url1">推流地址</h3>
								<h4></h4>
							</div>
						</div>
					</div>
				</div>
				
				<div class="container">
					<div class="row">
						<div class="col-sm-12">
							<div class="subscribe_area"> <!-- Subscribe -->
								<!-- form section -->	
								
							<video id="live_video" class="video-js vjs-default-skin" controls preload="auto" width="inherit" height="650px" poster="http://vjs.zencdn.net/v/oceans.png" data-setup="{}">
								<source src="{{channel_url.url_rtmp}}" type="rtmp/flv">
								<p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
							</video>


								
								<!-- end form section -->		
							</div>
						</div>
					</div>
				</div>
			
			</div>	<!-- //Home area-->
			
			<div style="clear:both;"></div>
			
			<input type='hidden' id='id' value="{{object.id}}">
			<input type='hidden' id='status' value="{{object.status}}">

<!--
##  Under button_area // Mainmenu area 
=============================================================================== -->				
			
			<div class="container navbar">   <!-- Under button -->
				<div class="row">
					<div class="col-sm-12 ">
						<div class="button_area" id="sticker"> <!-- sticker menu for mobile layout -->
							<ul id="nav">
								<li id="scrollbar" >
									<h3 id="live_start" class="btn_menu services btn  btn-lg " >开始直播</h3>	
									<h3 id="live_over"  class="btn_menu team_member btn  btn-lg" >结束直播</h3>
							
								</li>	
							</ul>	
						</div>
					</div>
				</div>
			</div> <!-- //Under button -->
		</div>  <!-- //End main div  -->
		<script src="/static/course/sbtp_53_obey/js/jquery-1.9.1.min.js"></script>	  
		<script type="text/javascript" src="/static/course/js/control.js"></script>
		<script src="http://vjs.zencdn.net/5.20.1/video.js"></script>
	</body>

</html>




<!-- 
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Video.js | HTML5 Video Player</title>
 

    <link href="http://vjs.zencdn.net/5.20.1/video-js.css" rel="stylesheet">
    <script src="http://vjs.zencdn.net/5.20.1/videojs-ie8.min.js"></script>
    
</head>
<body>

  <video id="example_video_1" class="video-js vjs-default-skin" controls preload="auto" width="1280" height="720" poster="http://vjs.zencdn.net/v/oceans.png" data-setup="{}">
    <source src="rtmp://live.ilaus.vc/1_sasdfasfa/1505306603151_sasdfasfa" type="rtmp/flv">
    
    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
  </video>
  
  <script src="http://vjs.zencdn.net/5.20.1/video.js"></script>
</body>

</html> -->