live/live/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import  settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^anchor/', include('anchor.urls', namespace="anchor")),
    url(r'^course/', include('course.urls', namespace="course")),
    url(r'^category/', include('category.urls', namespace="category")),
    url(r'^audience/', include('audience.urls', namespace="audience")),
    url(r'^management/', include('management.urls', namespace="management")),
    url(r'^index/', include('index.urls', namespace="index")),




    #直播api
    url(r'^courses/', include('course.api_urls')),
    url(r'^categories/', include('category.api_urls')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

live/management/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib.auth.views import logout_then_login, password_change

from . import views



urlpatterns = [
    # 前端用户
    url(r'^management_list/$', views.AuthList.as_view(), name='management_list'),
    url(r'^management_add/$', views.AuthAdd.as_view(), name='management_add'),
    # url(r'^management_edit/(?P<pk>\w*)/$', views.AnchorEdit.as_view(), name='management_edit'),
    url(r'^logout/$', logout_then_login, name='logout'),
    url(r'^login/$', views.LoginForm.as_view(), name='login'),



]

live/management/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

live/management/views.py
# -*- coding: utf-8 -*-
import os
import uuid
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, FormView, TemplateView, DetailView, View
from django.contrib.auth.hashers import make_password, check_password

from django.contrib.auth import authenticate, logout, login
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm

from django.contrib.auth.models import User

from audience.models import UserInfo

from base.views import OwnerList
from audience.utils import get_unique_username



@method_decorator(login_required, name='dispatch')
class AuthList(OwnerList):
    template_name = 'management/list.html'
    context_object_name = 'obj_list'
    model_class = UserInfo
    form_fields = []
    # 默认查询，为提供同一个表根据不同的默认条件获取不同意义的数据
    default_filters = {}
    request_key = ["tel", "name"]

    def get_queryset(self):
        # handler_history()
        user = self.request.user
        object_list = super(AuthList, self).get_queryset()
        return object_list


@method_decorator(login_required, name='dispatch')
class AuthAdd(generic.TemplateView):
    template_name = "management/management_add.html"

    def post(self, request):
        post_data = request.POST
        password = post_data.get('password')
        name = post_data.get('name')
        tel = post_data.get('tel')
        user_id = user_id=str(uuid.uuid1()).replace('-', '')        
        if not password:
            return JsonResponse({'result': 'fail', 'message': u'请输入密码!'})
        
        user = User.objects.filter(username=name)
        if user:
            return JsonResponse({'result': 'fail', 'message': u'该用户名已经存在!'})
        with transaction.atomic():
            user = User.objects.create_user(username=name, password=password, is_staff=True)

            user.save()


            userinfo = UserInfo(name=name, passwd=make_password(password), user_id=user_id, tel=tel,
                                type=1, owner=user)
            userinfo.save()

            
        return redirect("management:management_list")

class LoginForm(FormView):
    '''
    后台登录
    '''
    template_name = 'management/login.html'
    form_class = AuthenticationForm

    def get_context_data(self, **kwargs):
        context = super(LoginForm, self).get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next')
        return context

    def post(self, request):
        try:
            username = request.POST.get('username')
            password = request.POST.get('password')
            next = request.POST.get('next', None)

            user = authenticate(username=username, password=password)
            if not user:
                messages.error(request, u'用户名密码不匹配')
                user_info_list = UserInfo.objects.filter(tel=username)
                if len(user_info_list) == 1:
                    user_info = user_info_list.first()
                    if not check_password(password, user_info.passwd):

                        # 如果该方式检测不能成功登录，则使用自定义加密方式进行验证
                        password = user_info.user_id + settings.SECRET_KEY + password
                        password = hashlib.new('md5', password.encode("utf8")).hexdigest()

                        if password != user_info.passwd:
                            messages.error(request, u'用户名密码不匹配')
                            return redirect('system:login')

                    # 处理完判断则代表可以登录
                    user = user_info.owner
            if not user.is_superuser and not user.is_staff:
                messages.error(request, u'权限不足，不能登录后台')
                return render(request, 'management/login.html')
    
            if next:
                    response = redirect(next)
            else:
                response = redirect('anchor:anchor_list')
      
            login(self.request, user)
            
            return response

        except Exception as e:
            messages.error(request, u'用户名或者密码错误')
            return render(request, 'management/login.html')

live/management/templates/management/list.html
{% extends "include/assets.html" %}
{% block main%}
{% load request_args %}
	<main class="main-cont content mCustomScrollbar">
            <div class="page-wrap">
                <!--开始::内容-->
                <section class="page-hd">
                    <header>
                        <h2 class="title">后台用户管理</h2>
                        <p class="title-description">
                        <a href="{% url 'management:management_add' %}" target="_blank">添加管理员</a>
                        </p>
                    </header>
                    <hr>
                </section>
                <div class="panel panel-default">
                    <section id="unseen">
                            <form action="" method="get">

                                <div class="span6">

                              
                                
                                    <div class="form-group fl">
                                        <label class="control-label fl">手机号:&nbsp;&nbsp;</label>
                                        <div class="fl">
                                            <input type="text" name="tel" class="form-control phone"
                                                   aria-controls="dynamic-table" value="{{ request.GET|ck_request_args:'tel' }}">
                                        </div>
                                    </div>
                                    <div class="form-group fl">
                                        <label class="control-label fl">姓名:&nbsp;&nbsp;</label>
                                        <div class="fl">
                                            <input type="text" name="name" class="form-control name"
                                                   aria-controls="dynamic-table" value="{{ request.GET|ck_request_args:'name' }}">
                                        </div>
                                    </div>

                                    <div class=" fl ">
                                        <div class="fl">
                                            <button class="btn btn-info fl search-user "
                                                    style="padding-left: 15px; padding-right: 15px;"
                                                    type="submit">查找
                                            </button>
                                        </div>
                                    </div>
                                </div>

                            </form>
                            <table class="table table-bordered table-striped table-condensed">
                                <thead>
                                <tr>
                                    <th style="display: none"></th>
                                    <th hidden>编号</th>
                                    <th>姓名</th>
                                    <th class="numeric">手机号</th>
                                    <th class="numeric">注册日期</th>
                                   
                                    <th class="numeric">操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% load paginate_tags %}
                                {% paginate obj_list 10 %}

                                {% for user in obj_list %}
                                    <tr>
                                        <td style="display: none" class="td-id"><input name="{{ objct.id }}" class="id"/>
                                        </td>
                                        <td hidden>{{ user.id }}</td>
                                        <td>{{ user.name }}</td>
                                        <td class="numeric">{{ user.tel }}</td>
                                        <td class="numeric">{{ user.create_time | date:"Y-m-d H:i" }}</td>
                             
                                        <td class="numeric opt">      

                                                <a href="/anchor/anchor_edit/{{ user.id }}/" >编辑</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <div class="row-fluid">
                                <div class="span6">
                                    <div class="dataTables_info" id="dynamic-table_info">
                                    </div>
                                </div>
                                <div class="span6">
                                    <div class="dataTables_paginate paging_bootstrap pagination ">
                                        <ul>
                                            {% include 'include/pagination.html' %}
                                        </ul>

                                    </div>

                                </div>
                            </div>
                        </section>
                    </div>
                </section>
                </div>
                <!--开始::结束-->
            </div>
        </main>
     
{% endblock %}
{% block js %}
    <script type="text/javascript" src="/static/anchor/js/func.js"></script>
{% endblock %}

live/management/templates/management/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="#" type="image/png">

    <title>Login</title>

    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style-responsive.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{% static 'assets/js/html5shiv.js' %}"></script>
    <script src="{% static 'assets/js/respond.min.js' %}"></script>
    <![endif]-->
</head>

<body class="login-body">


<div class="container">

    <form class="form-signin" action="{% url 'management:login' %}" method="post">
        {% csrf_token %}
        <div class="form-signin-heading text-center" style="color:#48995b; font-size: 20px;">
            <h1 class="sign-title"></h1>
            {#            <img src="{% static 'assets/images/logo.png' %}" width="270">#}
            {#            <img src="media/{{ third.log }}" width="270">#}
            <br>后台管理系统
        </div>
        <div class="login-wrap">
            <input type="text" name="username" class="form-control" placeholder="账号" autofocus>
            <input type="password" name="password" class="form-control" placeholder="密码">
            <input type="password" name="next" hidden value="{% if next %}{{ next }}{% endif %}">

            <button class="btn btn-lg btn-login btn-block" style="outline: none;" type="submit">
                <i class="fa fa-check"></i>
            </button>

            <div class="registration">
                Sign In to operate.
            </div>
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
                <span class="pull-right"> </span>
            </label>
        </div>
    </form>

    {% if next %}
        <div class="panel panel-danger layer_abso">
            <div class="panel-heading"><h3 class="panel-title">权限不足，请使用其他账号登录</h3></div>
        </div>
    {% endif %}

    {% if messages %}
        {% for message in messages %}
            <div class="panel panel-danger layer_abso">
                <div class="panel-heading"><h3 class="panel-title">{{ message }}</h3></div>
            </div>
        {% endfor %}

    {% endif %}
</div>


<!-- Placed js at the end of the document so the pages load faster -->

<!-- Placed js at the end of the document so the pages load faster -->
<script src="{% static 'assets/js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/modernizr.min.js' %}"></script>
<script src="{% static 'user/js/user.js' %}"></script>

</body>
</html>

live/management/templates/management/management_add.html
{% extends "include/assets.html" %}
{% load staticfiles %}

{% block main%}
    <main class="main-cont content mCustomScrollbar">
            <div class="page-wrap">
                <!--开始::内容-->
               <div class="panel-body">
                    <section id="unseen">
                        <div>
                            <form action="{% if action %}{{ action }}{% else %}{% url 'management:management_add' %}{%endif%}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                
                                <div class="form-group-col-2">
                                    <div class="form-label">姓名</div>
                                    <div class="form-cont">
                                        <input type="text" name="name" value="{{ object.name }}" class="form-control form-boxed" style="width:300px;">
                                    </div>
                                </div>
                                <div class="form-group-col-2">
                                    <div class="form-label">手机号码：</div>
                                    <div class="form-cont">
                                        <input type="text"  name="tel" value="{{ object.tel }}" class="form-control form-boxed" style="width:300px;">
                                    
                                    </div>
                                </div>
                                <div class="form-group-col-2">
                                    <div class="form-label">密码</div>
                                    <div class="form-cont">
                                        <input type="text"  name="password"  class="form-control form-boxed" style="width:300px;">
                                    
                                    </div>
                                </div>
                               
                                <div class="form-group-col-2">
                                    <div class="form-label">性别：</div>
                                    <div class="form-cont">
                                        <label class="radio">
                                            <input type="radio" value="1" {% if object.sex == 1 %} checked="checked" {% endif %} name="sex"/>
                                            <span>男士</span>
                                        </label>
                                        <label class="radio">
                                            <input type="radio" value="2"  name="sex"  {% if object.sex == 2 %} checked="checked" {% endif %} />
                                            <span>女士</span>
                                        </label>
                                        
                                    </div>
                                </div>
                                <div class="form-group-col-2">

                               
                                <div class="form-group-col-2">
                                    <div class="form-label">邮箱</div>
                                    <div class="form-cont">
                                        <input type="text" name="e_mail"   value="{{ object.e_mail }}" class="form-control form-boxed" style="width:300px;">
                                    </div>
                                </div>
                                
                    
                        <div class="cutbox_20px clear_Both"></div>
                        <div class="cutbox_20px clear_Both"></div>
                        <div class="clear_Both lh2em">
                            <label class="col-sm-2 tl"></label>
                            <div class="col-sm-10">
                                <button class="verify btn btn-info submit" style="padding-left: 15px; padding-right: 15px;" type="submit">保存</button>
                            </div>
                        </div>
                            </form>
                        <div class="cutbox_20px clear_Both"></div>
                        <div class="cutbox_20px clear_Both"></div>
                    </section>
                </div>
                 
                <!--开始::结束-->
            </div>
        </main>
     
{% endblock %}